[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  functions = "netlify/functions"
  command = "echo 'Dev server running'"
  port = 8000

# Environment variables for production (set these in Netlify dashboard)
# SMTP_HOST = your SMTP server
# SMTP_PORT = 587 or 465
# SMTP_USER = your email username  
# SMTP_PASS = your email password
# ADMIN_EMAIL = email to receive form submissions
# OPENAI_API_KEY = your OpenAI API key for chatbot (optional)

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"